# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_coordtransform.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Coordtransform(object):
    def setupUi(self, Coordtransform):
        Coordtransform.setObjectName("Coordtransform")
        Coordtransform.resize(527, 543)
        self.OK = QtWidgets.QDialogButtonBox(Coordtransform)
        self.OK.setGeometry(QtCore.QRect(350, 510, 171, 32))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        self.OK.setFont(font)
        self.OK.setOrientation(QtCore.Qt.Horizontal)
        self.OK.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.OK.setObjectName("OK")
        self.X = QtWidgets.QLineEdit(Coordtransform)
        self.X.setGeometry(QtCore.QRect(10, 110, 113, 27))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.X.setFont(font)
        self.X.setObjectName("X")
        self.Y = QtWidgets.QLineEdit(Coordtransform)
        self.Y.setGeometry(QtCore.QRect(140, 110, 113, 27))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.Y.setFont(font)
        self.Y.setObjectName("Y")
        self.inputcrs = QtWidgets.QLineEdit(Coordtransform)
        self.inputcrs.setGeometry(QtCore.QRect(270, 110, 113, 27))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.inputcrs.setFont(font)
        self.inputcrs.setObjectName("inputcrs")
        self.results = QtWidgets.QTextBrowser(Coordtransform)
        self.results.setGeometry(QtCore.QRect(10, 350, 501, 101))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.results.setFont(font)
        self.results.setObjectName("results")
        self.label = QtWidgets.QLabel(Coordtransform)
        self.label.setGeometry(QtCore.QRect(10, 70, 281, 17))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.outputcrs = QtWidgets.QLineEdit(Coordtransform)
        self.outputcrs.setGeometry(QtCore.QRect(400, 110, 113, 27))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.outputcrs.setFont(font)
        self.outputcrs.setObjectName("outputcrs")
        self.label_2 = QtWidgets.QLabel(Coordtransform)
        self.label_2.setGeometry(QtCore.QRect(60, 90, 21, 17))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Coordtransform)
        self.label_3.setGeometry(QtCore.QRect(190, 90, 21, 17))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Coordtransform)
        self.label_4.setGeometry(QtCore.QRect(275, 90, 111, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Coordtransform)
        self.label_5.setGeometry(QtCore.QRect(401, 90, 121, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setItalic(False)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.transform = QtWidgets.QPushButton(Coordtransform)
        self.transform.setGeometry(QtCore.QRect(400, 150, 97, 27))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        self.transform.setFont(font)
        self.transform.setObjectName("transform")
        self.label_6 = QtWidgets.QLabel(Coordtransform)
        self.label_6.setGeometry(QtCore.QRect(20, 330, 61, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.clear = QtWidgets.QPushButton(Coordtransform)
        self.clear.setGeometry(QtCore.QRect(290, 150, 97, 27))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setItalic(False)
        self.clear.setFont(font)
        self.clear.setObjectName("clear")
        self.label_8 = QtWidgets.QLabel(Coordtransform)
        self.label_8.setGeometry(QtCore.QRect(240, 10, 271, 51))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_8.setTextFormat(QtCore.Qt.PlainText)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.line = QtWidgets.QFrame(Coordtransform)
        self.line.setGeometry(QtCore.QRect(6, 60, 511, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_9 = QtWidgets.QLabel(Coordtransform)
        self.label_9.setGeometry(QtCore.QRect(30, 0, 221, 61))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap(":/plugins/coordtransform/logo.png"))
        self.label_9.setObjectName("label_9")
        self.label_7 = QtWidgets.QLabel(Coordtransform)
        self.label_7.setGeometry(QtCore.QRect(10, 190, 211, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_10 = QtWidgets.QLabel(Coordtransform)
        self.label_10.setGeometry(QtCore.QRect(10, 260, 221, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(Coordtransform)
        self.label_11.setGeometry(QtCore.QRect(80, 480, 21, 17))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(Coordtransform)
        self.label_12.setGeometry(QtCore.QRect(230, 480, 21, 17))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(Coordtransform)
        self.label_13.setGeometry(QtCore.QRect(60, 460, 251, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.inputproj4 = QtWidgets.QTextBrowser(Coordtransform)
        self.inputproj4.setGeometry(QtCore.QRect(10, 210, 501, 41))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.inputproj4.setFont(font)
        self.inputproj4.setObjectName("inputproj4")
        self.outputproj4 = QtWidgets.QTextBrowser(Coordtransform)
        self.outputproj4.setGeometry(QtCore.QRect(10, 280, 501, 41))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.outputproj4.setFont(font)
        self.outputproj4.setObjectName("outputproj4")
        self.trfX = QtWidgets.QTextBrowser(Coordtransform)
        self.trfX.setGeometry(QtCore.QRect(20, 500, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.trfX.setFont(font)
        self.trfX.setObjectName("trfX")
        self.trfY = QtWidgets.QTextBrowser(Coordtransform)
        self.trfY.setGeometry(QtCore.QRect(170, 500, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.trfY.setFont(font)
        self.trfY.setObjectName("trfY")

        self.retranslateUi(Coordtransform)
        self.OK.accepted.connect(Coordtransform.accept)
        self.OK.rejected.connect(Coordtransform.reject)
        QtCore.QMetaObject.connectSlotsByName(Coordtransform)

    def retranslateUi(self, Coordtransform):
        _translate = QtCore.QCoreApplication.translate
        Coordtransform.setWindowTitle(_translate("Coordtransform", "Coordtransform"))
        self.label.setText(_translate("Coordtransform", "USAGE: Input x, y and epsg/user defined values"))
        self.label_2.setText(_translate("Coordtransform", "X"))
        self.label_3.setText(_translate("Coordtransform", "Y"))
        self.label_4.setText(_translate("Coordtransform", "INPUT EPSG/USER"))
        self.label_5.setText(_translate("Coordtransform", "OUTPUT EPSG/USER"))
        self.transform.setText(_translate("Coordtransform", "Transform"))
        self.label_6.setText(_translate("Coordtransform", "RESULTS"))
        self.clear.setText(_translate("Coordtransform", "Clear"))
        self.label_8.setText(_translate("Coordtransform", "X,Y point coordtransform\n"
" Copyright (C) 2018 Giuseppe De Marco\n"
"www.d2gis.com"))
        self.label_7.setText(_translate("Coordtransform", "INPUT EPSG/USER To PROJ4"))
        self.label_10.setText(_translate("Coordtransform", "OUTPUT EPSG/USER To PROJ4"))
        self.label_11.setText(_translate("Coordtransform", "X"))
        self.label_12.setText(_translate("Coordtransform", "Y"))
        self.label_13.setText(_translate("Coordtransform", "TRANSFORMED COORDINATES"))

import resources_rc
